import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Analytics } from '@vercel/analytics/react';
import { ArrowDown, ArrowUpRight, Award, BookOpen, Check, Code2, Database, ExternalLink, MapPin, Menu, X } from 'lucide-react';
import './styles.css';

const experience = [
  { role: 'Azure Data Engineering Intern', company: 'Cognizant', date: 'Jan 2026 — Apr 2026', place: 'Chennai', text: 'Built scalable Azure data workflows, from multi-source ingestion to structured transformation and delivery.', bullets: ['Designed end-to-end ETL workflows with Azure Data Factory', 'Built a retail pipeline using Bronze, Silver, and Gold Medallion layers', 'Worked with Azure Synapse Analytics to improve data quality and usability'], tags: ['Azure Data Factory', 'Synapse Analytics', 'ETL', 'Medallion Architecture'] },
  { role: 'AI Automation Intern', company: 'Friday Technologies Ltd', date: 'Jul 2025 — Nov 2025', place: 'United Kingdom · Remote', text: 'Automated operational workflows and deployed intelligent voice experiences for client-facing processes.', bullets: ['Built workflows with n8n, GoHighLevel, and Make.com', 'Integrated voice agents using Vapi and Retell', 'Collaborated across teams on AI-led process optimization'], tags: ['n8n', 'Make.com', 'Vapi', 'Retell'] },
  { role: 'AI Intern', company: 'CDW Technologies', date: 'Jan 2025', place: 'Chennai', text: 'Developed prompt-driven NLP systems and grounded LLM applications.', bullets: ['Implemented Retrieval-Augmented Generation pipelines', 'Benchmarked model outputs for accuracy and relevance', 'Built domain-aware text generation workflows'], tags: ['LLMs', 'RAG', 'NLP', 'Prompt Engineering'] },
  { role: 'Machine Learning Intern', company: 'Aristo Creative Technology', date: 'Nov 2024 — Dec 2024', place: 'Chennai', text: 'Built and evaluated practical machine-learning solutions on real-world datasets.', bullets: ['Applied feature engineering across regression and classification tasks', 'Evaluated models using standard performance metrics', 'Delivered data-backed insights from experiment results'], tags: ['Python', 'Scikit-learn', 'Feature Engineering', 'Model Evaluation'] }
];

const projects = [
  { title: 'NOVA — Personalized AI Voice Assistant', kicker: 'Featured · 2025—2026', description: 'A context-aware desktop assistant that turns natural-language voice or text into real actions across browser, email, calendar, files, VS Code, and system utilities.', details: ['LLM-based intent routing', 'Real-time FastAPI + WebSockets', 'Speech and speaker verification'], tags: ['Llama 3.3', 'Groq API', 'FastAPI', 'React', 'WebSockets'], href: 'https://github.com/Srishtijais16/Voice-Assistant', featured: true },
  { title: 'Medical Health Chatbot', kicker: '2024—2025', description: 'A grounded healthcare Q&A assistant using LLMs, RAG, and a curated knowledge base for fast, context-aware responses.', tags: ['RAG', 'LLMs', 'NLP', 'Groq API'] },
  { title: 'Image-Based Product Recommendation', kicker: '2024', description: 'An e-commerce tool that extracts visual features from uploaded images and ranks similar products with cosine similarity.', tags: ['Computer Vision', 'OpenCV', 'Feature Extraction'], href: 'https://github.com/Srishtijais16/E-Commerce-Image-Similarity' }
];

const skillGroups = [
  ['Programming', ['Python', 'C', 'C++']],
  ['AI & Machine Learning', ['Machine Learning', 'NLP', 'Generative AI', 'LLMs', 'RAG', 'Model Evaluation']],
  ['Frameworks & Libraries', ['NumPy', 'Pandas', 'Scikit-learn', 'Matplotlib', 'OpenCV', 'FastAPI', 'React']],
  ['Azure / Data Engineering', ['Azure Data Factory', 'Azure Synapse', 'ETL Design', 'Data Warehousing', 'Medallion Architecture']],
  ['Databases / SQL', ['MySQL', 'SQL Workbench', 'Window Functions', 'CTEs', 'Data Modeling', 'Query Optimization']],
  ['AI Automation', ['n8n', 'Make.com', 'GoHighLevel', 'Vapi', 'Retell']],
  ['Analytics / Visualization', ['Power BI', 'Tableau', 'Pandas', 'Matplotlib']]
];

const certificates = [
  { category: 'AI & Machine Learning', title: 'Generative AI for Beginners', issuer: 'Udemy', date: 'Mar 2026', file: '/certificates/ai-ml/generative-ai-for-beginners-udemy-2026.jpg' },
  { category: 'AI & Machine Learning', title: 'Introduction to Data Analytics and AI', issuer: 'Udemy', date: 'Mar 2026', file: '/certificates/ai-ml/introduction-to-data-analytics-and-ai-udemy-2026.jpg' },
  { category: 'AI & Machine Learning', title: 'Generative AI Applications & Python Fundamentals', issuer: 'GUVI · HCL', date: 'Mar 2025', file: '/certificates/ai-ml/generative-ai-applications-python-fundamentals-guvi-hcl-2025.png' },
  { category: 'AI & Machine Learning', title: 'Data Science & Machine Learning', issuer: 'Udemy', date: 'Jun 2025', file: '/certificates/ai-ml/data-science-and-machine-learning-udemy-2025.jpg' },
  { category: 'Cloud & Data Engineering', title: 'Azure Data Factory: Data Engineering', issuer: 'Udemy', date: '2026', file: '/certificates/cloud-data-engineering/azure-data-factory-data-engineering-udemy-2026.pdf' },
  { category: 'Cloud & Data Engineering', title: 'Azure Synapse Analytics for Data Engineers', issuer: 'Udemy', date: '2026', file: '/certificates/cloud-data-engineering/azure-synapse-analytics-data-engineering-udemy-2026.pdf' },
  { category: 'Cloud & Data Engineering', title: 'Cloud Computing Fundamentals', issuer: 'Udemy', date: 'Mar 2026', file: '/certificates/cloud-data-engineering/cloud-computing-fundamentals-udemy-2026.jpg' },
  { category: 'SQL & Data Warehousing', title: 'SQL for Data Analysis: Advanced Querying', issuer: 'Udemy', date: 'Feb 2026', file: '/certificates/sql-databases/sql-for-data-analysis-advanced-querying-udemy-2026.jpg' },
  { category: 'SQL & Data Warehousing', title: 'Relational Database Design', issuer: 'Udemy', date: 'Feb 2026', file: '/certificates/sql-databases/relational-database-design-udemy-2026.jpg' },
  { category: 'SQL & Data Warehousing', title: 'Data Warehouse ETL Testing & Data Quality', issuer: 'Udemy', date: 'Mar 2026', file: '/certificates/sql-databases/data-warehouse-etl-testing-data-quality-management-udemy-2026.jpg' },
  { category: 'Analytics', title: 'Power BI and Tableau', issuer: 'Imarticus Learning', date: 'Apr 2024', file: '/certificates/data-analytics/power-bi-and-tableau-imarticus-2024.jpeg' },
  { category: 'Analytics', title: 'Data Analytics with Python · Elite', issuer: 'NPTEL · IIT Roorkee', date: 'Jan—Apr 2025', file: '/certificates/data-analytics/data-analytics-with-python-nptel-2025.jpeg' }
];

const achievements = [
  { title: 'Certificate of Merit — ALTRUIXX 2K25', meta: 'SRM Valliammai Engineering College · 2025' },
  { title: 'Semi-Finalist — National Level Hackathon', meta: 'Saveetha Engineering College · 2024' },
  { title: 'ICCET 2026 Paper Presentation', meta: 'Personalized AI Voice Assistant for Desktop Automation', file: '/certificates/achievements/iccet-paper-presentation-personalized-ai-voice-assistant-2026.jpeg' },
  { title: 'HackerRank Certified', meta: 'Python · SQL Basic & Intermediate · Problem Solving', href: 'https://www.hackerrank.com/profile/srishtijaiswal51' },
  { title: 'HDCA Certified', meta: 'CSC Computer Education · MySQL, C, C++ & Python' }
];

function SectionTitle({ eyebrow, title, intro }) { return <div className="section-title reveal"><span>{eyebrow}</span><h2>{title}</h2>{intro && <p>{intro}</p>}</div> }
function Tags({ items }) { return <div className="tags">{items.map(x => <span key={x}>{x}</span>)}</div> }

function Navbar() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const fn = () => setScrolled(scrollY > 40); addEventListener('scroll', fn, { passive: true }); return () => removeEventListener('scroll', fn) }, []);
  const links = ['About', 'Experience', 'Projects', 'Skills', 'Credentials', 'Contact'];
  return <header className={`nav ${scrolled ? 'scrolled' : ''}`}><a className="brand" href="#top" aria-label="Home"><span>SJ</span><i /></a><button className="menu-btn" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button><nav className={open ? 'open' : ''}>{links.map(x => <a key={x} href={`#${x.toLowerCase()}`} onClick={() => setOpen(false)}>{x}</a>)}<a className="nav-cta" href="mailto:srishtijaiswal51@gmail.com">Let’s talk <ArrowUpRight size={15}/></a></nav></header>
}

function Hero() {
  return <section id="top" className="hero"><div className="hero-grid"/><div className="orb orb-a"/><div className="orb orb-b"/><div className="hero-copy"><div className="availability"><i/> Open to AI engineering opportunities</div><p className="hero-kicker">Aspiring AI Engineer · Chennai, India</p><h1>Srishti<br/><em>Jaiswal</em></h1><p className="hero-statement">Building intelligent systems, AI-powered applications, scalable data pipelines, and automation solutions.</p><p className="keywords">AI / ML <b>·</b> LLMs <b>·</b> RAG <b>·</b> Azure <b>·</b> Backend <b>·</b> Automation</p><div className="hero-actions"><a className="button primary" href="#projects">View projects <ArrowDown size={17}/></a><a className="button secondary" href="#contact">Connect <ArrowUpRight size={17}/></a></div></div><div className="hero-visual" aria-hidden="true"><div className="system-card"><div className="system-top"><span><i/> intelligence.system</span><small>ONLINE</small></div><div className="neural"><svg viewBox="0 0 500 360"><g className="lines"><path d="M55 180L155 80L255 135L350 65L445 160M55 180L150 270L255 220L350 295L445 160M155 80L150 270M255 135L255 220M350 65L350 295"/></g><g className="nodes">{[[55,180],[155,80],[255,135],[350,65],[445,160],[150,270],[255,220],[350,295]].map(([cx,cy],i)=><circle key={i} cx={cx} cy={cy} r={i===4?9:6}/>)}</g></svg></div><div className="system-log"><span><i>01</i> intent.route</span><span><i>02</i> context.retrieve</span><span><i>03</i> action.execute</span></div></div></div><a href="#about" className="scroll-cue"><span>Scroll to explore</span><ArrowDown size={14}/></a></section>
}

function About() { return <section id="about" className="section"><SectionTitle eyebrow="01 / About" title="Engineering practical intelligence."/><div className="about-grid"><div className="portrait-wrap reveal"><div className="portrait-frame"><img src="/assets/srishti-jaiswal-profile.jpeg" alt="Srishti Jaiswal"/><span>AI / DS</span></div></div><div className="about-copy reveal"><p className="lead">I build at the intersection of <strong>applied AI, data engineering, and automation</strong>—turning complex technical ideas into systems people can actually use.</p><p>My work spans LLM applications, retrieval-augmented generation, computer vision, Azure data pipelines, and business automation. I care about thoughtful architecture, grounded model outputs, and clean end-to-end execution.</p><div className="stats"><div><strong>8.6</strong><span>CGPA / 10</span></div><div><strong>04</strong><span>Internships</span></div><div><strong>20</strong><span>Public repositories</span></div></div><a className="text-link" href="/documents/srishti-jaiswal-resume.pdf" target="_blank">View résumé <ArrowUpRight size={16}/></a></div></div></section> }

function Experience() { return <section id="experience" className="section section-alt"><SectionTitle eyebrow="02 / Experience" title="From models to production workflows." intro="Hands-on experience across cloud data engineering, AI automation, LLM systems, and machine learning."/><div className="timeline">{experience.map((x,i)=><article className="exp-card reveal" key={x.company}><div className="exp-index">0{i+1}</div><div className="exp-head"><div><h3>{x.role}</h3><p>{x.company}</p></div><div className="exp-meta"><span>{x.date}</span><small><MapPin size={13}/>{x.place}</small></div></div><p className="exp-summary">{x.text}</p><ul>{x.bullets.map(b=><li key={b}><Check size={14}/>{b}</li>)}</ul><Tags items={x.tags}/></article>)}</div></section> }

function Projects() { return <section id="projects" className="section"><SectionTitle eyebrow="03 / Selected work" title="Systems designed to do real work."/><div className="project-grid">{projects.map((p,i)=><article className={`project-card reveal ${p.featured?'featured':''}`} key={p.title}><div className="project-number">0{i+1}</div><div className="project-content"><span className="project-kicker">{p.kicker}</span><h3>{p.title}</h3><p>{p.description}</p>{p.details && <ul>{p.details.map(x=><li key={x}>{x}</li>)}</ul>}<Tags items={p.tags}/>{p.href && <a href={p.href} target="_blank" rel="noreferrer">View repository <ArrowUpRight size={16}/></a>}</div>{p.featured && <div className="project-terminal" aria-hidden="true"><div><i/><i/><i/><span>nova_core.py</span></div><pre><b>01</b> voice_input = listen()<br/><b>02</b> intent = llm.route(voice_input)<br/><b>03</b> context = retrieve(intent)<br/><b>04</b> <em>await</em> execute(intent, context)<br/><br/><span>✓ action completed in 1.8s</span></pre></div>}</article>)}</div></section> }

function Skills() { return <section id="skills" className="section section-alt"><SectionTitle eyebrow="04 / Technical toolkit" title="A stack built around intelligence and scale."/><div className="skills-grid">{skillGroups.map(([title,skills],i)=><article className="skill-card reveal" key={title}><div className="skill-top"><span>0{i+1}</span>{i<2?<Code2/>:<Database/>}</div><h3>{title}</h3><Tags items={skills}/></article>)}</div></section> }

function Education() { return <section id="education" className="section"><SectionTitle eyebrow="05 / Education" title="Built on AI & data science fundamentals."/><article className="education-card reveal"><div className="edu-icon"><BookOpen/></div><div><span>2022 — 2026</span><h3>B.Tech in Artificial Intelligence and Data Science</h3><p>Velammal Engineering College · Anna University · Chennai</p></div><div className="cgpa"><strong>8.6</strong><span>CGPA / 10</span></div></article></section> }

function Credentials() {
  const [active, setActive] = useState(null); const cats = [...new Set(certificates.map(x=>x.category))];
  useEffect(()=>{ const fn=e=>{if(e.key==='Escape')setActive(null)}; addEventListener('keydown',fn); return()=>removeEventListener('keydown',fn)},[]);
  return <><section id="credentials" className="section section-alt"><SectionTitle eyebrow="06 / Certifications" title="Verified learning, carefully curated." intro="A focused selection across AI, cloud data engineering, SQL, and analytics."/><div className="cert-groups">{cats.map(cat=><div className="cert-group reveal" key={cat}><h3>{cat}<span>{String(certificates.filter(x=>x.category===cat).length).padStart(2,'0')}</span></h3><div>{certificates.filter(x=>x.category===cat).map(c=><button className="cert-row" key={c.title} onClick={()=>setActive(c)}><span><strong>{c.title}</strong><small>{c.issuer} · {c.date}</small></span><span className="view-cert">View <ArrowUpRight size={15}/></span></button>)}</div></div>)}</div></section><section id="achievements" className="section"><SectionTitle eyebrow="07 / Recognition" title="Milestones beyond the classroom."/><div className="achievement-grid">{achievements.map((a,i)=><article className="achievement-card reveal" key={a.title}><Award/><span>0{i+1}</span><h3>{a.title}</h3><p>{a.meta}</p>{a.file?<button onClick={()=>setActive({title:a.title,file:a.file})}>View credential <ArrowUpRight size={15}/></button>:a.href?<a href={a.href} target="_blank" rel="noreferrer">View profile <ArrowUpRight size={15}/></a>:null}</article>)}</div></section>{active&&<div className="modal" role="dialog" aria-modal="true" aria-label={active.title} onMouseDown={e=>{if(e.target===e.currentTarget)setActive(null)}}><div className="modal-panel"><div className="modal-head"><div><small>Verified credential</small><strong>{active.title}</strong></div><button aria-label="Close certificate" onClick={()=>setActive(null)}><X/></button></div>{active.file.endsWith('.pdf')?<iframe src={active.file} title={active.title}/>:<img src={active.file} alt={`${active.title} certificate`} loading="lazy"/>}</div></div>}</>
}

function Publication() { return <section id="publications" className="section section-alt"><SectionTitle eyebrow="08 / Research" title="Exploring natural interfaces for automation."/><a className="paper reveal" href="/documents/personalized-ai-voice-assistant-paper.pdf" target="_blank"><div className="paper-icon"><BookOpen/></div><div><span>Research manuscript · 2026</span><h3>Personalized AI Voice Assistant for Desktop Automation</h3><p>Co-authored research on NOVA’s LLM intent routing, modular service execution, speech pipeline, and speaker authentication architecture.</p><small>Srishti Jaiswal S · Joncy J · Amirthavalli S · Yuvashree P</small></div><ArrowUpRight/></a></section> }

function Contact() { return <section id="contact" className="contact section"><div className="contact-glow"/><span className="contact-kicker">09 / Let’s build something intelligent</span><h2>Have an idea worth<br/><em>engineering?</em></h2><p>I’m open to AI engineering roles, thoughtful collaborations, and ambitious technical projects.</p><a className="email-link" href="mailto:srishtijaiswal51@gmail.com">srishtijaiswal51@gmail.com <ArrowUpRight/></a><div className="socials"><a href="https://linkedin.com/in/srishti-jaiswal-a92796257" target="_blank" rel="noreferrer"><ExternalLink/>LinkedIn</a><a href="https://github.com/Srishtijais16" target="_blank" rel="noreferrer"><Code2/>GitHub</a><a href="https://www.hackerrank.com/profile/srishtijaiswal51" target="_blank" rel="noreferrer"><Code2/>HackerRank</a><a href="https://instagram.com/s.r.i.s.h.t.i.__16" target="_blank" rel="noreferrer"><ExternalLink/>Instagram</a></div></section> }

function Footer() { return <footer><a className="brand" href="#top"><span>SJ</span><i/></a><p>Designed & engineered for clarity, curiosity, and impact.</p><span>© {new Date().getFullYear()} Srishti Jaiswal{/* · Property of Siddharth Magesh */}</span></footer> }

function App(){ useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>o.observe(el));return()=>o.disconnect()},[]); return <><Navbar/><main><Hero/><About/><Experience/><Projects/><Skills/><Education/><Credentials/><Publication/><Contact/></main><Footer/></> }

createRoot(document.getElementById('root')).render(<React.StrictMode><App/><Analytics/></React.StrictMode>);
